#!/usr/bin/php -q
<?php
require_once("/usr/local/emhttp/plugins/speedtest/include/parse_cfg.php");

echo "Internet bandwidth test started\n\n";
shell_exec("echo -e 'Internet bandwidth test started' | logger -tspeedtest");

$options = "";
if ( $speedtest_list == "manual")
	$options .= " --server ".$speedtest_server;
if ($speedtest_secure == "secure")
	$options .= " --secure";
if ($speedtest_share == "share")
	$options .= " --share"; 
if ($speedtest_units == "bytes")
		$options .= " --bytes";

$command = "speedtest  ".$options." 2>/dev/null";
$handle = popen($command, 'r');

$xml = simplexml_load_file($speedtest_filename);
$test = $xml->addChild('test');
$test->addAttribute('name', round(microtime(true) * 1000));

ob_start();

while(!feof($handle)) {
    $buffer = trim(fgets($handle));
    $msg = "$buffer\n\n";
    	$output = explode(": ", $buffer);
    if ((strpos($output[0], "Hosted by")) !== false) {
    	$test->addAttribute('host', substr($output[0],10));
    	$test->addAttribute('ping', $output[1]);
    	$msg .= "Testing download speed...\n\n";
    }elseif ((strpos($buffer, "Download")) !== false) {
    	$test->addAttribute('download', $output[1]);
    	$msg .= "Testing upload speed...\n\n";
    }elseif ((strpos($buffer, "Upload")) !== false) {
    	$test->addAttribute('upload', $output[1]);
    }elseif ((strpos($buffer, "Share results")) !== false) {
    	$test->addAttribute('share', $output[1]);
    }elseif (((strpos($buffer, "Testing download")) !== false) || ((strpos($buffer, "Testing upload")) !== false)) {
    	$msg = "";}
    echo "$msg";
  
    ob_flush();
}

pclose($handle);

ob_end_flush();

$xml->asXML($speedtest_filename);

shell_exec("echo -e 'Internet bandwidth test completed' | logger -tspeedtest");
?>
