#!/bin/sh
prog="libvirtwol"
LIBVIRTWOL="/usr/local/emhttp/plugins/$prog/scripts/$prog.py"
LOCKFILE="/var/lock/$prog"
PIDFILE="/var/run/$prog.pid"
CONFIG="/boot/config/domain.cfg"

# read our configuration
[ -e $CONFIG ] &&	source $CONFIG

if [ $WOL == "enable" ]; then
	# no-op if already running
	if [ ! -r $PIDFILE ]; then
		sleep 1
		nohup /usr/bin/python $LIBVIRTWOL $BRNAME > /dev/null 2>&1 & echo $! > $PIDFILE &
		touch $LOCKFILE
		TIMER=0
		while [ ! -e $PIDFILE ]; do
			sleep 1
			let TIMER=$TIMER+1
      		if [ $TIMER -gt 5 ]; then
	         	  echo -n "$PIDFILE not created"
		           break
   		  	fi
		done
	else
	echo "$prog is already running"
	fi
else
echo "$prog is not enabled"
fi
