#!/bin/bash
CFGFILE="/boot/config/plugins/aesir-plugin/aesir-plugin.cfg"

# read our configuration
[ -f $CFGFILE ] && source $CFGFILE

if [ $SERVICE = enable ]; then
	/usr/local/emhttp/plugins/aesir-plugin/scripts/start
fi

